# Spring Boot 应用配置
server:
  port: 23333
  servlet:
    context-path: /shiro

# Spring 框架配置
spring:
  # 数据源配置 - MySQL
  datasource:
    # MySQL 数据库连接配置
    url: jdbc:mysql://localhost:3306/nacos?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 连接池配置 (HikariCP)
    hikari:
      # 连接池名称
      pool-name: ShiroHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数
      maximum-pool-size: 20
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接最大生存时间（毫秒）
      idle-timeout: 600000
      # 连接最大生存时间（毫秒）
      max-lifetime: 1800000

  # JPA 配置
  jpa:
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQLDialect
    # 显示 SQL 语句
    show-sql: true
    # Hibernate 配置
    hibernate:
      # DDL 模式: create-drop(重新创建), update(更新), validate(验证), none(不操作)
      ddl-auto: update
      # 命名策略：使用下划线命名
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # SQL 格式化输出
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 批处理大小
        jdbc:
          batch_size: 20
        # 启用二级缓存
        cache:
          use_second_level_cache: false

  # 应用名称
  application:
    name: shiro-mysql-demo

  # Spring Session配置（替代Shiro Session管理）
#  session:
#    # Session存储方式: none(内存), redis, mongodb, jdbc等
#    store-type: none  # 开发环境使用内存，生产环境建议使用redis
#    # Session超时时间（秒）
#    timeout: 1800  # 30分钟
#    # Cookie配置
#    cookie:
#      # Cookie名称
#      name: JSESSIONID
#      # Cookie路径
#      path: /
#      # 跨域Cookie设置（SameSite属性）
#      same-site: none  # 允许跨域携带Cookie
#      # HTTPS环境设为true，HTTP环境设为false
#      secure: false
#      # 允许JavaScript访问Cookie（便于前端获取sessionId）
#      http-only: false
#      # Cookie最大存活时间（-1表示会话级别）
#      max-age: -1

# 日志配置
logging:
  level:
    # 设置 Shiro 相关日志级别
    org.apache.shiro: DEBUG
    # 设置 Hibernate SQL 日志级别
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # 设置应用程序日志级别
    com.lxq.learn: DEBUG
    # 设置 Spring Security 日志级别
    org.springframework.security: DEBUG
  # 日志格式
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        # 暴露健康检查端点
        include: health,info
  endpoint:
    health:
      show-details: always

# 自定义应用配置
app:
  # 安全配置
  security:
    # 密码加密配置
    password:
      algorithm: MD5
      iterations: 1024
    # 会话配置
    session:
      timeout: 1800 # 30分钟（秒）
      max-active: 1000 # 最大活跃会话数

  # 数据库配置
  database:
    # 是否在启动时初始化测试数据
    init-test-data: true